[package]
name = "webrat"
version = "0.1.0"
edition = "2021"

[dependencies]


bevy = { version = "0.13.0",  default-features = true}
ratatui = { version = "0.26.1",  default-features = false }
bevy_ratatui = { version = "0.1.2"}


