/// A backend-agnostic virtual key representation.
///
/// This enum replaces the direct dependency on `rdev::Key`, allowing the library
/// to be used with any backend (crossterm, ratzilla, web events, etc.).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VirtualKey {
    Escape,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Backspace,
    Tab,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Return,
    CapsLock,
    ShiftLeft,
    ShiftRight,
    ControlLeft,
    ControlRight,
    Alt,
    AltGr,
    Space,
}

/// Maps a key name string (from layout files) to a `VirtualKey`.
pub fn virtual_key_from_name(name: &str) -> Option<VirtualKey> {
    match name.to_lowercase().as_str() {
        "esc" | "escape" => Some(VirtualKey::Escape),
        "1" => Some(VirtualKey::Num1),
        "2" => Some(VirtualKey::Num2),
        "3" => Some(VirtualKey::Num3),
        "4" => Some(VirtualKey::Num4),
        "5" => Some(VirtualKey::Num5),
        "6" => Some(VirtualKey::Num6),
        "7" => Some(VirtualKey::Num7),
        "8" => Some(VirtualKey::Num8),
        "9" => Some(VirtualKey::Num9),
        "0" => Some(VirtualKey::Num0),
        "back" | "backspace" => Some(VirtualKey::Backspace),
        "tab" => Some(VirtualKey::Tab),
        "q" => Some(VirtualKey::KeyQ),
        "w" => Some(VirtualKey::KeyW),
        "e" => Some(VirtualKey::KeyE),
        "r" => Some(VirtualKey::KeyR),
        "t" => Some(VirtualKey::KeyT),
        "y" => Some(VirtualKey::KeyY),
        "u" => Some(VirtualKey::KeyU),
        "i" => Some(VirtualKey::KeyI),
        "o" => Some(VirtualKey::KeyO),
        "p" => Some(VirtualKey::KeyP),
        "enter" | "return" => Some(VirtualKey::Return),
        "caps" | "capslock" => Some(VirtualKey::CapsLock),
        "a" => Some(VirtualKey::KeyA),
        "s" => Some(VirtualKey::KeyS),
        "d" => Some(VirtualKey::KeyD),
        "f" => Some(VirtualKey::KeyF),
        "g" => Some(VirtualKey::KeyG),
        "h" => Some(VirtualKey::KeyH),
        "j" => Some(VirtualKey::KeyJ),
        "k" => Some(VirtualKey::KeyK),
        "l" => Some(VirtualKey::KeyL),
        "lshift" | "shift" => Some(VirtualKey::ShiftLeft),
        "rshift" => Some(VirtualKey::ShiftRight),
        "z" => Some(VirtualKey::KeyZ),
        "x" => Some(VirtualKey::KeyX),
        "c" => Some(VirtualKey::KeyC),
        "v" => Some(VirtualKey::KeyV),
        "b" => Some(VirtualKey::KeyB),
        "n" => Some(VirtualKey::KeyN),
        "m" => Some(VirtualKey::KeyM),
        "ctrl" | "lctrl" => Some(VirtualKey::ControlLeft),
        "rctrl" => Some(VirtualKey::ControlRight),
        "alt" | "lalt" => Some(VirtualKey::Alt),
        "ralt" | "altgr" => Some(VirtualKey::AltGr),
        "space" => Some(VirtualKey::Space),
        _ => None,
    }
}
